name: example
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number with a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  daliuren:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-daliuren.git
  theme:
    git:
      url: http://192.168.0.165:3000/xuan/theme.git
  xuan_common_ui:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-common-ui.git
  metaphysics_chart_ui:
    git:
      url: http://192.168.0.165:3000/xuan/metaphysics-chart-ui.git
  persistence_assets:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: assets
  repository_interface_daliuren:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-daliuren.git
  provider: ^6.1.5+1
  persistence_drift:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: drift
  persistence_preferences:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: preferences
  shared_preferences: ^2.2.0
  drift: ^2.30.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  enumeration:
    git:
      url: http://192.168.0.165:3000/xuan/enumeration.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you just need to
  # use the Icons class in your code.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/da_liu_ren/

  # An image asset can refer to one or more resolution-aware "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

dependency_overrides:
  persistence_core:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: core
  persistence_drift:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: drift
  persistence_preferences:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-storage.git
      path: preferences
  metaphysics_core:
    git:
      url: http://192.168.0.165:3000/xuan/metaphysics-core.git
  xuan_gua_core:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-gua-core.git
  xuan_four_zhu_card:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-four-zhu-card.git
  theme:
    git:
      url: http://192.168.0.165:3000/xuan/theme.git
  xuan_common_ui:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-common-ui.git
  metaphysics_chart_ui:
    git:
      url: http://192.168.0.165:3000/xuan/metaphysics-chart-ui.git
  calendar:
    git:
      url: http://192.168.0.165:3000/xuan/calendar.git
  repository_interface_four_zhu_card:
    git:
      url: http://192.168.0.165:3000/xuan/repository-interface-four-zhu-card.git
  persistence_domain:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-domain.git
  xuan_time_location:
    git:
      url: http://192.168.0.165:3000/xuan/xuan-time-location.git
