// lib/data/datasources/local/drift_database.dart

// Main Drift database definition file for the DaLiuRen application.
// This file includes:
// 1. Table definitions (e.g., for Ju Mappings, Yu Ding Entries, Preset Pans).
// 2. Custom TypeConverters for storing complex Dart objects as basic SQL types (usually JSON strings).
// 3. The AppDatabase class that extends Drift's GeneratedDatabase.
// 4. DAO registrations.
// 5. Database connection opening logic.

import 'dart:io'; // For File operations
import 'package:drift/drift.dart';
// import 'package:drift/native.dart'; // For NativeDatabase (SQLite on mobile/desktop)
import 'package:drift_flutter/drift_flutter.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart'; // For finding the app's documents directory
import 'package:path/path.dart' as p; // For path manipulation
import 'package:common/database/connection.dart' as impl;
// Import all table definitions
import '../../../models/each_class_data_model.dart';
import '../../../models/four_class_data_model.dart';
import '../../../models/three_chuan_data_model.dart';
import 'converters/four_class_converter.dart';
import 'converters/map_string_string_converter.dart';
import 'converters/set_string_converter.dart';
import 'converters/three_chuan_converter.dart';
import 'tables/ju_mappings.dart';
import 'tables/yu_ding_entries.dart';
import 'tables/preset_pans.dart';
import 'tables/db_initialization_flags.dart';

// Import domain models
import 'package:common/enums.dart' as common_enums_actual;
import '../../../../model/enum_gui_ren.dart' as domain_gui_ren_actual;

// This will be generated by drift.
part 'drift_database.g.dart';

// --------- Database Class Definition ---------
/// The main database class for the application, built with Drift.
/// It lists all tables and DAOs that are part of this database.
@DriftDatabase(tables: [
  JuMappings,
  YuDingEntries,
  PresetPans,
  DbInitializationFlags,
], daos: [
  // LiuRenDao, // DAO for Liu Ren specific operations
])
class DaLiuRenAppDatabase extends _$DaLiuRenAppDatabase {
  DaLiuRenAppDatabase([QueryExecutor? e])
      : super(
          e ??
              driftDatabase(
                name: 'liuren_database',
                native: const DriftNativeOptions(
                  databaseDirectory: getApplicationSupportDirectory,
                ),
                web: DriftWebOptions(
                  sqlite3Wasm: Uri.parse('sqlite3.wasm'),
                  driftWorker: Uri.parse('drift_worker.js'),
                  onResult: (result) {
                    if (result.missingFeatures.isNotEmpty) {
                      print(
                        'Using ${result.chosenImplementation} due to unsupported '
                        'browser features: ${result.missingFeatures}',
                      );
                    }
                  },
                ),
              ),
        );

  /// Constructor for testing that uses an in-memory database
  DaLiuRenAppDatabase.forTesting(QueryExecutor executor) : super(executor);

  @override
  int get schemaVersion => 1;

  @override
  MigrationStrategy get migration {
    return MigrationStrategy(
      onCreate: (Migrator m) async {
        await m.createAll();
      },
      beforeOpen: (details) async {
        if (details.wasCreated) {
          // Create a bunch of default values so the app doesn't look too empty
          // on the first start.
        }

        await impl.validateDatabaseSchema(this);
      },
    );
  }

  Future<void> _executeSqlScript(String scriptPath) async {
    final sqlScript = await rootBundle.loadString(scriptPath);
    final statements = sqlScript
        .split(';')
        .map((s) => s.trim())
        .where((s) => s.isNotEmpty)
        .toList();

    for (final statement in statements) {
      await customStatement(statement);
    }
  }
}

/// Opens the database connection.
/// Uses [LazyDatabase] to open the connection on first use, potentially in a background isolate.
// LazyDatabase _openConnection() {
//   return LazyDatabase(() async {
//     final dbFolder = await getApplicationDocumentsDirectory();
//     final file = File(p.join(dbFolder.path, 'daliuren_db.sqlite'));
//     return NativeDatabase.createInBackground(file);
//   });
// }

// Helper extension for EachClassDataModel to make copyWith available for defaults.
extension on EachClassDataModel {
  EachClassDataModel copyWith({
    int? order,
    common_enums_actual.DiZhi? sky,
    common_enums_actual.DiZhi? ground,
    domain_gui_ren_actual.GuiRen? guiRen,
    bool? isFirstClass,
    bool? isSkyKeDayGan,
    bool? isSkySameYinYangWithDayGan,
    int? sheHaiTimes,
    List<int>? otherSameSkyGroundIndexList,
  }) {
    return EachClassDataModel(
      order: order ?? this.order,
      sky: sky ?? this.sky,
      ground: ground ?? this.ground,
      guiRen: guiRen ?? this.guiRen,
      isFirstClass: isFirstClass ?? this.isFirstClass,
      isSkyKeDayGan: isSkyKeDayGan ?? this.isSkyKeDayGan,
      isSkySameYinYangWithDayGan:
          isSkySameYinYangWithDayGan ?? this.isSkySameYinYangWithDayGan,
      sheHaiTimes: sheHaiTimes ?? this.sheHaiTimes,
      otherSameSkyGroundIndexList:
          otherSameSkyGroundIndexList ?? this.otherSameSkyGroundIndexList,
    );
  }
}
