// lib/data/datasources/local/dao/liuren_dao.dart

import 'package:drift/drift.dart';
import '../drift_database.dart';
import '../tables/db_initialization_flags.dart'; // Import the main database class (AppDatabase) and table DBOs (e.g., JuMappingEntryDb)

part 'liuren_dao.g.dart'; // Auto-generated by Drift

/// Data Access Object (DAO) for Liu Ren related data.
/// This class uses the Drift accessor pattern to define methods for interacting
/// with the tables defined in [AppDatabase]. It handles all database operations
/// like inserting, querying, updating, and deleting data.
@DriftAccessor(tables: [
  // JuMappings, // Table for Ju Mappings
  // YuDingEntries, // Table for Yu Ding Da Liu Ren entries
  // PresetPans, // Table for pre-calculated/preset pans
  DbInitializationFlags // Table for database initialization flags
])
class LiuRenDao extends DatabaseAccessor<DaLiuRenAppDatabase>
    with _$LiuRenDaoMixin {
  /// The main database instance, injected via constructor.
  final DaLiuRenAppDatabase db;

  /// Constructor that takes the main [AppDatabase] instance.
  LiuRenDao(this.db) : super(db);

  // --- DbInitializationFlags Methods ---

  /// Retrieves a specific database initialization flag by its [key].
  /// Returns the [DbInitializationFlag] DBO if found, otherwise null.
  Future<DbInitializationFlag?> getInitializationFlag(String key) {
    return (select(db.dbInitializationFlags)
          ..where((tbl) => tbl.flagKey.equals(key)))
        .getSingleOrNull();
  }

  /// Sets or updates a database initialization flag.
  /// Uses `insertOnConflictUpdate` to either insert a new flag or update an existing one.
  Future<void> setInitializationFlag(String key, bool isSet) {
    // Creates a Companion object for insertion/update.
    // `insertOnConflictUpdate` handles cases where the flagKey might already exist.
    return into(db.dbInitializationFlags).insertOnConflictUpdate(
      DbInitializationFlagsCompanion.insert(
          flagKey: Value(key), isSet: Value(isSet)),
    );
  }

  // --- JuMappings Methods ---

  /// Performs a bulk insert of [JuMappingsCompanion] entries.
  /// If entries with the same primary key exist, they will be updated.
  Future<void> bulkInsertJuMappings(List<JuMappingsCompanion> entries) async {
    // `batch` ensures all operations are performed in a single transaction for efficiency.
    await batch((batch) {
      batch.insertAllOnConflictUpdate(db.juMappings, entries);
    });
  }

  /// Finds a specific Ju Mapping entry based on day JiaZi, time DiZhi, and YinYang value.
  /// Returns the [JuMappingEntryDb] DBO if found, otherwise null.
  Future<JuMappingEntryDb?> findJuMapping({
    required String dayJiaZiName,
    required String timeDiZhiName,
    required String yinYangValue,
  }) {
    return (select(db.juMappings)
          ..where((tbl) => tbl.dayJiaZiName.equals(dayJiaZiName))
          ..where((tbl) => tbl.timeDiZhiName.equals(timeDiZhiName))
          ..where((tbl) => tbl.yinYangValue.equals(yinYangValue)))
        .getSingleOrNull(); // Expects at most one result.
  }

  /// Counts the total number of entries in the JuMappings table.
  Future<int> countJuMappings() {
    // Uses an expression to count rows. `id` refers to the implicit rowid.
    final countExp = db.juMappings.rowId.count();
    final query = selectOnly(db.juMappings)..addColumns([countExp]);
    return query
        .map((row) => row.read(countExp))
        .getSingle()
        .then((value) => value ?? 0);
  }

  // --- YuDingEntries Methods ---

  /// Performs a bulk insert of [YuDingEntriesCompanion].
  /// Updates existing entries on conflict.
  Future<void> bulkInsertYuDingEntries(
      List<YuDingEntriesCompanion> entries) async {
    await batch((batch) {
      batch.insertAllOnConflictUpdate(db.yuDingEntries, entries);
    });
  }

  /// Finds a specific Yu Ding entry based on day JiaZi and Ju Name (GanShangDiZhi).
  /// Returns the [YuDingEntryDb] DBO if found, otherwise null.
  Future<YuDingEntryDb?> findYuDingEntry({
    required String dayJiaZiName,
    required String juName, // This is the DiZhi name of the GanShangShen.
  }) {
    return (select(db.yuDingEntries)
          ..where((tbl) => tbl.dayJiaZiName.equals(dayJiaZiName))
          ..where((tbl) => tbl.juName.equals(juName)))
        .getSingleOrNull();
  }

  /// Counts the total number of entries in the YuDingEntries table.
  Future<int> countYuDingEntries() {
    final countExp = db.yuDingEntries.dayJiaZiName
        .count(distinct: false); // Count one of the PK columns.
    final query = selectOnly(db.yuDingEntries)..addColumns([countExp]);
    return query
        .map((row) => row.read(countExp))
        .getSingle()
        .then((value) => value ?? 0);
  }

  // --- PresetPans Methods ---

  /// Performs a bulk insert of [PresetPansCompanion].
  /// Updates existing entries on conflict.
  Future<void> bulkInsertPresetPans(List<PresetPansCompanion> entries) async {
    await batch((batch) {
      batch.insertAllOnConflictUpdate(db.presetPans, entries);
    });
  }

  /// Finds a specific Preset Pan entry based on day JiaZi, ShiChen DiZhi, and YinYang Dun.
  /// Returns the [PresetPanEntryDb] DBO if found, otherwise null.
  Future<PresetPanEntryDb?> findPresetPan({
    required String dayJiaZiName,
    required String shiChenName,
    required String yinYangDun,
  }) {
    return (select(db.presetPans)
          ..where((tbl) => tbl.dayJiaZiName.equals(dayJiaZiName))
          ..where((tbl) => tbl.shiChenName.equals(shiChenName))
          ..where((tbl) => tbl.yinYangDun.equals(yinYangDun)))
        .getSingleOrNull();
  }

  /// Counts the total number of entries in the PresetPans table.
  Future<int> countPresetPans() {
    final countExp = db.presetPans.dayJiaZiName
        .count(distinct: false); // Count one of the PK columns.
    final query = selectOnly(db.presetPans)..addColumns([countExp]);
    return query
        .map((row) => row.read(countExp))
        .getSingle()
        .then((value) => value ?? 0);
  }

  /// Clears all data from all Liu Ren related tables.
  /// Useful for re-initialization or testing purposes.
  Future<void> clearAllData() async {
    // Perform deletions in a transaction for atomicity.
    await db.transaction(() async {
      await delete(db.juMappings).go();
      await delete(db.yuDingEntries).go();
      await delete(db.presetPans).go();
      await delete(db.dbInitializationFlags)
          .go(); // Also clear initialization flags.
    });
    print("DAO: All LiuRen data cleared from the database.");
  }
}
