// lib/data/models/placeholder_data_model.dart

// This is a placeholder.
// Actual data models (DTOs) that map directly to data sources (JSON, Drift tables, API responses)
// will be created here.
// Many existing models from `lib/model` might be moved or adapted here if they are
// simple data containers primarily used for serialization/deserialization from assets.

// For example, if you have a JSON structure for a preset pan:
/*
import 'package:json_annotation/json_annotation.dart';
import 'package:metaphysics_core/enums.dart'; // Assuming enums like JiaZi, DiZhi are here or in domain

part 'placeholder_data_model.g.dart'; // Generated by json_serializable

@JsonSerializable()
class PresetPanJsonModel {
  final String dayJiaZi; // Store as string, convert to enum later
  final String shiChen;  // Store as string
  // ... other fields from your JSON

  PresetPanJsonModel({required this.dayJiaZi, required this.shiChen});

  factory PresetPanJsonModel.fromJson(Map<String, dynamic> json) => _$PresetPanJsonModelFromJson(json);
  Map<String, dynamic> toJson() => _$PresetPanJsonModelToJson(this);
}
*/

class PlaceholderDataModel {
  final String id;
  final String name;

  PlaceholderDataModel({required this.id, required this.name});
}
